name: Build Firmware

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Clone itspriddle/q2-qmk
        uses: actions/checkout@v3
      - name: Get version
        id: version
        run: ./.github/scripts/get-version >> $GITHUB_ENV
      - name: Clone qmk/qmk_firmware
        run: git clone --depth=1 --recurse-submodules --shallow-submodules https://github.com/qmk/qmk_firmware.git
      - name: Install qmk deps
        run: cd qmk_firmware && ./util/qmk_install.sh && python3 -m pip install qmk
      - name: Copy custom keymaps
        run: cp -rp keyboards/keychron/q2/ansi_encoder/keymaps/josh qmk_firmware/keyboards/keychron/q2/ansi_encoder/keymaps
      - name: Compile firmware
        run: |
          cd qmk_firmware
          make keychron/q2/ansi_encoder:josh
          cp keychron_q2_ansi_encoder_josh.bin "../pkg/keychron_q2_josh-${{ env.Q2_QMK_VERSION }}.bin"
      - name: Upload compiled firmware (build artifact)
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: actions/upload-artifact@v3
        with:
          name: Keychron Q2 Josh (${{ env.Q2_QMK_VERSION }}-HEAD)
          path: pkg/keychron_q2_josh-${{ env.Q2_QMK_VERSION }}.bin
      - name: Package firmware for tagged release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd pkg
          gzip -c "keychron_q2_josh-${{ env.Q2_QMK_VERSION }}.bin" > "keychron_q2_josh-${{ env.Q2_QMK_VERSION }}.gz"
      - name: Upload compiled firmware for tagged release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            pkg/keychron_q2_josh-${{ env.Q2_QMK_VERSION }}.gz
