name: Build Firmware

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Clone itspriddle/q2-qmk
        uses: actions/checkout@v3
      - name: Clone qmk/qmk_firmware
        run: git clone --depth=1 --recurse-submodules --shallow-submodules https://github.com/qmk/qmk_firmware.git
      - name: Install qmk deps
        run: cd qmk_firmware && ./util/qmk_install.sh && python3 -m pip install qmk
      - name: Copy custom keymaps
        run: cp -rp keyboards/keychron/q2/ansi_encoder/keymaps/josh qmk_firmware/keyboards/keychron/q2/ansi_encoder/keymaps
      - name: Compile firmware
        run: cd qmk_firmware && make keychron/q2/ansi_encoder:josh
      - name: Package firmware
        run: ls qmk_firmware && mkdir build/keychron_q2_ansi_encoder_josh && cp qmk_firmware/keychron_q2_ansi_encoder_josh.bin qmk_firmware/keychron_q2_ansi_encoder_josh.hex build/keychron_q2_ansi_encoder_josh && cd build && zip -r keychron_q2_ansi_encoder_josh.zip keychron_q2_ansi_encoder_josh
      - name: Upload compiled firmware (build artifact)
        uses: actions/upload-artifact@v3
        with:
          name: Keychron Q2 ANSI Encoder QMK Firmware (Josh)
          path: qmk_firmware/keychron_q2_ansi_encoder_josh.zip
      - name: Upload compiled firmware (tagged release)
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            qmk_firmware/keychron_q2_ansi_encoder_josh.zip
